### PR TITLE
Added zacharysang

### PR DESCRIPTION
**Pull request by zacharysang**

### CODE REVIEW

**Comment by kurtlewis** [comment]
You got a typo at the end of your bio fyi
> I usually use with Nodejs

**Comment by zacharysang** [comment]
As you can tell from my descriptive commit message, I have now fixed said typo. Merge me in! ;)

**Comment by kurtlewis** [comment]
I stole the honors from @isiah-lloyd :)

**Comment by kurtlewis** [comment]
Wait this is why I shouldn't steal honors from Isiah -  you don't meet the meeting requirement. You better go to another meeting or I'll revert this commit

**Comment by zacharysang** [comment]
Social engineering at its finest

**Comment by isiah-lloyd** [comment]
@kurtlewis Merge privileges revoked

**Pull request merged**
